name: DevSecOps Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security-scan:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      # -------------------------
      # GitLeaks - Secret Scanning
      # -------------------------
      - name: Install GitLeaks
        run: |
          LATEST_TAG=$(curl -s https://api.github.com/repos/gitleaks/gitleaks/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
          VERSION=${LATEST_TAG#v}
          curl -sSFL "https://github.com/gitleaks/gitleaks/releases/download/${LATEST_TAG}/gitleaks_${VERSION}_linux_x64.tar.gz" -o /tmp/gitleaks.tar.gz
          tar -xzf /tmp/gitleaks.tar.gz -C /tmp
          chmod +x /tmp/gitleaks
          /tmp/gitleaks version

      - name: GitLeaks Secret Scan
        run: |
          /tmp/gitleaks detect --source . --no-git

      # -------------------------
      # Semgrep - SAST
      # -------------------------
      - name: Semgrep SAST Scan
        run: |
          source ~/semgrep-env/bin/activate
          semgrep scan --config=auto .

      # -------------------------
      # Docker Build
      # -------------------------
      - name: Build Docker Image
        run: |
          docker build -t devsecops-demo:ci .

      # -------------------------
      # Trivy - Container Scan
      # -------------------------
      - name: Trivy Container Scan
        run: |
          trivy image \
            --severity CRITICAL,HIGH \
            --exit-code 1 \
            devsecops-demo:ci
